### ISSUE TITLE
Default initializer for Students t is faulty

### ISSUE THREAD

**Issue by andrewjlee0** [roads/psiz#18]
The default n_dim parameter isn't initialized correctly when no value is provided by the user. 

#bug

**Comment by roads** [comment]
Hi @andrewjlee0,

Good catch. The `n_dim` argument has been removed (commit 3e49e236ce30f104257a97a8fe8514ca2de37a2f) since it is redundant with the free parameter `alpha`. Originally this was included to help users pick a reasonable default (i.e., van der Maaten suggests `alpha=n_dim-1`). This decision is now left up to the user.
